[browser]
gatherUsageStats = false

[server]
maxUploadSize = 5
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#1a4480"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e8eaed"
textColor = "#1b1b1b"
font = "sans serif"